#≈‰÷√ ˝æ›‘¥
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/air_conditioner?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource